version: 2

project_name: unstuck

before:
  hooks:
    - go mod tidy
    - go generate ./...

builds:
  - id: unstuck
    main: ./cmd/unstuck
    binary: unstuck
    env:
      - CGO_ENABLED=0
    goos:
      - linux
      - darwin
      - windows
    goarch:
      - amd64
      - arm64
    ignore:
      - goos: windows
        goarch: arm64
    ldflags:
      - -s -w
      - -X main.version={{.Version}}
      - -X main.commit={{.Commit}}
      - -X main.date={{.Date}}

archives:
  - id: unstuck
    format: tar.gz
    name_template: "{{ .ProjectName }}_{{ .Os }}_{{ .Arch }}"
    format_overrides:
      - goos: windows
        format: zip

checksum:
  name_template: 'checksums.txt'

snapshot:
  version_template: "{{ incpatch .Version }}-next"

changelog:
  sort: asc
  filters:
    exclude:
      - '^docs:'
      - '^test:'
      - '^ci:'
      - Merge pull request
      - Merge branch

brews:
  - name: unstuck
    repository:
      owner: sozercan
      name: homebrew-tap
      token: "{{ .Env.HOMEBREW_TAP_GITHUB_TOKEN }}"
    folder: Formula
    homepage: "https://github.com/sozercan/unstuck"
    description: "Diagnose and remediate Kubernetes resources stuck in Terminating state"
    license: "MIT"
    install: |
      bin.install "unstuck"
    test: |
      system "#{bin}/unstuck", "--version"
